### ISSUE TITLE
Assignment in #12

### ISSUE THREAD

**Issue by ghost** [fkling/jsbasics#14] opened 2016-03-12 23:33 UTC
In number 12 it says:
Assignment: foo = bar, assigns the value of the lhs to the rhs.
It should actually be:
Assignment: foo = bar, assigns the value of the rhs to the lhs.

**Comment by fkling** [comment] 2016-03-14 06:08
Duplicate of #6. Thanks though!

**Closed as completed by fkling** 2016-03-14 06:08 UTC
